package me.whale.common.enums.personal;

public enum LoginMethod {
    /**
     * use password
     */
    PASSWORD,
    /**
     * use passcode generated by authentication apps
     */
    PASSCODE,
    /**
     * use third-party authentication
     */
    THIRD_PARTY,
    ;
}
