version: "3.8"
services:
  mydb:
    image: docker.io/mysql/mysql-server:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - 30031:3306
    volumes:
      - ../conf.d/my.cnf:/etc/mysql/my.cnf
      - ../data/mysql-initdb.d:/docker-entrypoint-initdb.d/
      - /srv/mysql/data:/var/lib/mysql
      - /etc/ssl/certs/mysql:/etc/ssl/certs/mysql
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 100m

  pgdb:
    image: docker.io/library/postgres:${POSTGRES_VERSION}
    container_name: postgres
    ports:
      - 5000:5432
    volumes:
      - ../conf.d/postgres.conf:/etc/postgresql/postgresql.conf
      - ../data/postgres-initdb.d:/docker-entrypoint-initdb.d/
      - /srv/postgresql/data:/var/lib/postgresql/data
    networks:
      - database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_INITDB_ARGS=--data-checksums --encoding=UTF8 --locale=C --auth=scram-sha-256
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 100m

  redis-single:
    image: docker.io/library/redis:${REDIS_VERSION}
    container_name: redis-single
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - ../conf.d/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - /srv/redis/data:/data
    networks:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50m
        reservations:
          cpus: '0.1'
          memory: 20m

  oracle:
    image: container-registry.oracle.com/database/enterprise:${ORACLE_VERSION}
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - /srv/oracle/data:/opt/oracle/oradata
    networks:
      - database
    environment:
      - ORACLE_PWD=${ORACLE_PASS}
      - ENABLE_ARCHIVELOG=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g
        reservations:
          cpus: '0.5'
          memory: 2g

networks:
  mysql:
    driver: bridge
    name: mysql
  redis:
    driver: bridge
    name: redis
  database:
    driver: bridge
    name: database
