/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("me.whale.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

application {
    applicationDefaultJvmArgs = listOf(
        "-Dfile.encoding=UTF-8", "-Xms128m", "-Xmx512m",
        "-XX:+HeapDumpOnOutOfMemoryError", "-XX:HeapDumpPath=./java_pid<pid>.hprof", "-XX:+UseGCOverheadLimit",
        "-XX:+UseDynamicNumberOfGCThreads", "-XX:+UseZGC",
        "-Xlog:gc*:file=./build/%p_gc.log::filecount=10,filesize=100M"
    )
}

tasks.withType<JavaExec> {
    environment("APP_NAME", project.name)
}