server:
  port: ${BACKEND_PORT:8080}

spring:
  profiles:
    include: cache

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    shutdown:
      enabled: true